# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 08:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=52, null=True)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=5)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('elev', models.IntegerField(null=True)),
                ('original', models.BooleanField(default=True)),
                ('min_year', models.IntegerField(default=9999)),
                ('max_year', models.IntegerField(default=-9999)),
                ('missing_months', models.IntegerField(default=0)),
                ('complete_data_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('largest_gap', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(default='2019')),
                ('month', models.PositiveSmallIntegerField(default='1')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='populate_db.Station')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StationDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_station', models.BigIntegerField(db_index=True, default=0)),
                ('master_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_station', to='populate_db.Station')),
            ],
        ),
    ]
