# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 06:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_db', '0010_auto_20170224_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
