# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_db', '0013_auto_20180725_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_id',
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
