# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_db', '0014_auto_20180725_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
